version: '3'
services:
  master:
    container_name:
      master
    hostname:
      localhost
    ports:
      - "3012:3012"
    build: .
        #image: dude/man:v2
    # image: "intelliops/cronicle:latest"
    volumes:
      - /Users/arun/docker_volumes/data:/opt/cronicle/data:rw  
      - /Users/arun/docker_volumes/logs:/opt/cronicle/logs:rw
      - /Users/arun/docker_volumes/plugins:/opt/cronicle/plugins:rw
  slave:
    container_name:
      slave
    hostname:
      temp_localhost
    ports:
      - "3112:3012"
    build: .
        #image: dude/man:v2
    # image: "intelliops/cronicle:latest"
    volumes:
      - /Users/arun/docker_volumes/data:/opt/cronicle/data:rw
      - /Users/arun/docker_volumes/slave_data/logs:/opt/cronicle/logs:rw
      - /Users/arun/docker_volumes/slave_data/plugins:/opt/cronicle/plugins:rw