version: '3'
services:
  master:
    container_name:
      master_new
    hostname:
      master_node
    ports:
      - "3012:3012"
    build: 
      context: .
      args : 
        master: "true"
    image : "arun15/cronicle_multi_server"
    volumes:
      - /cronicle/data:/opt/cronicle/data:rw
      - /cronicle/logs:/opt/cronicle/logs:rw
      - /cronicle/plugins:/opt/cronicle/plugins:rw
  slave:
    hostname:
      slave_node_1
    container_name:
      slave_new
    ports:
      - "3112:3012"
    build: 
      context: .
      args : 
        master: "true"
    image: "arun15/cronicle_multi_server"
    volumes:
      - /cronicle/data:/opt/cronicle/data:rw
      - /cronicle/slave_data/logs:/opt/cronicle/logs:rw
      - /cronicle/slave_data/plugins:/opt/cronicle/plugins:rw
