version: "3.1"
services:
  master:
    container_name:
      master_new
    hostname:
      master_node
    ports:
      - "3012:3012"
    build: 
      args : 
        master: "true"
    image : "arun15/cronicle_multi_server"
    volumes:
      - /cronicle/data:/opt/cronicle/data:rw
      - /cronicle/logs:/opt/cronicle/logs:rw
      - /cronicle/plugins:/opt/cronicle/plugins:rw
    networks:
      - cronicle  
    deploy:
      mode: replicated
      replicas: 2
      labels: [APP=Master_label]
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
        window: 120s
      placement:
        constraints: [node.role == manager]
  slave:
    hostname:
      slave_node_1
    container_name:
      slave_new
    ports:
      - "3112:3012"
    build: 
      args : 
        master: "false"
    image: "arun15/cronicle_multi_server"
    volumes:
      - /cronicle/data:/opt/cronicle/data:rw
      - /cronicle/slave_data/logs:/opt/cronicle/logs:rw
      - /cronicle/slave_data/plugins:/opt/cronicle/plugins:rw
    networks:
      - cronicle  
    deploy:
      mode: replicated
      replicas: 1
      labels: [APP=Slave_label]
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
        window: 120s

networks:
  cronicle:

volumes:
  data:
  logs:
  plugins:
   